### PR TITLE
WIP update to basic-cli 0.13

### PR DESCRIPTION
**Pull request by Anton-4**

### CODE REVIEW

**Comment by Anton-4** [comment]
Valgrind on segmentation fault:
```
==75278== Memcheck, a memory error detector
==75278== Copyright (C) 2002-2022, and GNU GPL'd, by Julian Seward et al.
==75278== Using Valgrind-3.22.0 and LibVEX; rerun with -h for copyright info
==75278== Command: /home/username/gitrepos/examples2/examples/examples/SafeMath/main
==75278== 
==75278== 
==75278== Process terminating with default action of signal 11 (SIGSEGV): dumping core
==75278==  General Protection Fault
==75278==    at 0x12ED9A: List_walkTryHelp_392aebc0773ca1163ead8eb210e2c2aabca4fe4ded9f2b122a7dab30d082d98b (roc_app:0)
==75278==    by 0x1326D0: List_walkTry_2cc6e6d3c5a48a76ea218c439d44b6318e7bd267419a22dcb25b258a2c06a (roc_app:0)
==75278==    by 0x13190A: #UserApp_safeVariance_7f8c4a473141d41efa7657e3f378539f18179e0b2dff0f626f6dce25d295f (roc_app:0)
==75278==    by 0x131D46: #UserApp_main_92df2e9c67226884f739cd53c0493c2aabaabd406877a3b72a3e676dc54e081 (roc_app:0)
==75278==    by 0x133B45: _mainForHost_1fbc6d79b671ab88e8a9425cd46a77344c0f7ee34ea43fdcaf5a014c6759d (roc_app:0)
==75278==    by 0x133B69: roc__mainForHost_1_exposed_generic (roc_app:0)
==75278==    by 0x197643: rust_main (in /home/username/gitrepos/examples2/examples/examples/SafeMath/main)
==75278==    by 0x488110D: (below main) (in /nix/store/ddwyrxif62r8n6xclvskjyy6szdhvj60-glibc-2.39-5/lib/libc.so.6)
==75278== 
==75278== HEAP SUMMARY:
==75278==     in use at exit: 72 bytes in 2 blocks
==75278==   total heap usage: 2 allocs, 0 frees, 72 bytes allocated
==75278== 
==75278== LEAK SUMMARY:
==75278==    definitely lost: 0 bytes in 0 blocks
==75278==    indirectly lost: 0 bytes in 0 blocks
==75278==      possibly lost: 48 bytes in 1 blocks
==75278==    still reachable: 24 bytes in 1 blocks
==75278==         suppressed: 0 bytes in 0 blocks
==75278== Rerun with --leak-check=full to see details of leaked memory
==75278== 
==75278== For lists of detected and suppressed errors, rerun with: -s
==75278== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
Segmentation fault (core dumped)
```

**Comment by Anton-4** [comment]
We've solved a "General Protection Fault" before [here](https://github.com/roc-lang/roc/pull/3551#discussion_r922889080) we also have an unsolved General Protection Fault in #6813. That one was similar to here, inside `List_walkHelp` instead of `List_walkTryHelp`.

**Comment by bhansconnect** [comment]
Is this properly using an updated version of the compiler? Cause 0.13 requires the testing nightly compiler, right? I'm guessing it is related to the refcount on heap.

But could be something else for sure. Would be worth looking into list types being used and their expected alignments.

**Comment by Anton-4** [comment]
I was able to bisect this to https://github.com/roc-lang/roc/commit/c5a74bdc1254152f5faf9bd12ca3d10f6bf2ca8c

**Comment by Anton-4** [comment]
> Is this properly using an updated version of the compiler? Cause 0.13 requires the testing nightly compiler,

The ubuntu tests are using the latest TESTING release

**Comment by bhansconnect** [comment]
Interesting. Llvm should automatically be setting alignment for allocas based on the values stored in them. I wonder what's missing  🤔

**Comment by Anton-4** [comment]
Much smaller example with platform-switching rust platform:
```roc
app [main] { pf: platform "rust-platform/main.roc" }

safeVariance = \maybeEmptyList ->
        mean = Ok 5.0

        maybeEmptyList
        |> List.walkTry
            123.0
            (\_state, elem ->
                mean
                |> Result.try (\m -> Num.subChecked elem m)) # X - µ

main =

    varianceResult =
        [46, 69]
        |> safeVariance
        |> Result.map Num.toStr

    outputStr =
        when varianceResult is
            Ok str -> str
            Err Overflow -> "Error: Overflow: When calculating the variance, a number got too large to store in the available memory for the type."

    outputStr
```
It does work with this small change to `mean`:
```roc
app [main] { pf: platform "rust-platform/main.roc" }

safeVariance = \maybeEmptyList ->
        #mean = Ok 5.0

        maybeEmptyList
        |> List.walkTry
            123.0
            (\_state, elem ->
                Ok 5.0 # mean
                |> Result.try (\m -> Num.subChecked elem m)) # X - µ

main =

    varianceResult =
        [46, 69]
        |> safeVariance
        |> Result.map Num.toStr

    outputStr =
        when varianceResult is
            Ok str -> str
            Err Overflow -> "Error: Overflow: When calculating the variance, a number got too large to store in the available memory for the type."

    outputStr

```

**Comment by bhansconnect** [comment]
Interesting. That will be useful for debugging, but I won't have time to look until at least Friday. I guess the issue is somehow with lambda closure capture inputs. I wonder if they are aligned correctly. Maybe that is the bug.

**Comment by Anton-4** [comment]
For my smaller example, for commits before c5a74bdc1254152f5faf9bd12ca3d10f6bf2ca8c, if I build with the legacy linker, the executable produces no output (no segfault either). It works fine with the surgical linker. I even tried this with a commit from 4 months ago and the same thing happens. What's going wrong there is probably important for our current segfault.

Interesting valgrind diff between the surgical and legacy linker:
surgical
```
==100333== Command: examples/platform-switching/rocLovesRepro
==100333== 
64.0==100333== 
==100333== HEAP SUMMARY:
==100333==     in use at exit: 0 bytes in 0 blocks
==100333==   total heap usage: 12 allocs, 12 frees, 3,229 bytes allocated
==100333== 
```
legacy
```
==100614== Command: ./examples/platform-switching/rocLovesRepro
==100614== 
==100614== 
==100614== HEAP SUMMARY:
==100614==     in use at exit: 1,024 bytes in 1 blocks
==100614==   total heap usage: 2 allocs, 1 frees, 1,072 bytes allocated
==100614== 
```
Going to check this out with gdb next.

**Comment by Anton-4** [comment]
> the executable produces no output (no segfault either)

That one is solved by https://github.com/roc-lang/roc/pull/7012

**Comment by Anton-4** [comment]
Given that movaps needs 16 bit alignment, the align 16 in the memcpy could be wrong:
```llvm
define internal fastcc void @List_walkTryHelp_7f7e162ee4345c12acb2c8dddfd129c8c9ef562ecb31841cfff13d4789ffc2(%list.RocList %"3", i128 %"4", ptr %"5", i64 %"6", i64 %"7", ptr %0) !dbg !91 {
entry:
  %tag_alloca15 = alloca { [0 x i128], [2 x i64], i8, [15 x i8] }, align 8
  %tag_alloca = alloca { [0 x i128], [2 x i64], i8, [15 x i8] }, align 8
  %result_value = alloca { [0 x i128], [2 x i64], i8, [15 x i8] }, align 8
  %joinpoint_arg_alloca = alloca { [0 x i128], [2 x i64], i8, [15 x i8] }, align 8
  tail call fastcc void @"#Attr_#inc_1"(%list.RocList %"3", i64 1), !dbg !92
  call void @llvm.memcpy.p0.p0.i64(ptr noundef nonnull align 16 dereferenceable(32) %joinpoint_arg_alloca, ptr noundef nonnull align 16 dereferenceable(32) %"5", i64 32, i1 false), !dbg !92
  br label %joinpointcont, !dbg !92
```
Claude weighing in:
> There's a potential misalignment issue with `%joinpoint_arg_alloca`. It's allocated with 8-byte alignment but used with 16-byte alignment in the `memcpy` operation. This could lead to undefined behavior or performance issues on some architectures.

**Comment by Anton-4** [comment]
If I use 8 instead of the alignment [here](https://github.com/roc-lang/roc/blob/c5a74bdc1254152f5faf9bd12ca3d10f6bf2ca8c/crates/compiler/gen_llvm/src/llvm/build.rs#L3367) the issue is gone. For both alignments in `build_memcpy` the alignment of the `argument` is used, perhaps for the first alignment it should be calculated based on `joinpoint_arg` @bhansconnect?
```rust
            for (joinpoint_arg, argument) in joinpoint_args.iter().zip(arguments.iter()) {
                let (value, layout) = scope.load_symbol_and_layout(argument);

                match joinpoint_arg {
                    crate::llvm::scope::JoinPointArg::Alloca(alloca) => {
                        let (size, alignment) = layout_interner.stack_size_and_alignment(layout);
                        builder
                            .build_memcpy(
                                *alloca,
                                alignment,
                                value.into_pointer_value(),
                                alignment,
                                env.ptr_int().const_int(size as _, false),
                            )
                            .unwrap();
                    }
                    crate::llvm::scope::JoinPointArg::Phi(phi) => {
                        phi.add_incoming(&[(&value, current_block)]);
                    }
                }
            }
```

**Comment by Anton-4** [comment]
Issue fixed in https://github.com/roc-lang/roc/pull/7015

**Comment by Anton-4** [comment]
superseded by https://github.com/roc-lang/examples/pull/197

**Pull request closed without merging**
